### ISSUE TITLE
Errors in DMAN_demo.m

### ISSUE THREAD

**Issue by xdg2016** [jizhu1023/DMAN_MOT#2]
Hello, thanks for your works. When I run the DMAN_demo.m, there are some errors:
1、In MOT_track.m, the function MDP_value is lost
![image](https://user-images.githubusercontent.com/16351823/60142524-cc77f380-97ec-11e9-98fd-fdf0b4e346ea.png)
2、I copy the MDP_value.m from MDP project, however, there are too many parameters input to the MDP_value function.
![image](https://user-images.githubusercontent.com/16351823/60142622-27a9e600-97ed-11e9-809a-e74a5bfec2f5.png)

Would you please help me ? thank you very much !

**Comment by borguleabhijeet** [comment]
Thanks for your uploads:
The same issue is here! could you please also upload the training procedures?

**Comment by borguleabhijeet** [comment]
Having the same issue here! This file is missing. @jizhu1023  could please help ?

**Comment by keras0147** [comment]
Hi,  I also have the same problem.  MDP_value is lost in the repository. I tried to integrate MDP file with this code but the original MDP file use LK tracker and this project has incorporated with the ECO tracker. Would you please help?

**Comment by jizhu1023** [comment]
Sorry for the trouble. I have fixed the bug and updated the code. Feel free to let me know if you meet any problem when running the code : )

**Comment by xdg2016** [comment]
Thanks for your reply, the problems mentioned above is gone, however, I meet a new problem:
![image](https://user-images.githubusercontent.com/16351823/60851054-6b0c4780-a224-11e9-821a-92272b4b84c7.png)
This problem arises when I run DMAN_demo.m. The python socket server is:
![image](https://user-images.githubusercontent.com/16351823/60851238-ea9a1680-a224-11e9-9f0b-8ce78b46717c.png)
It seems that there is no similarity. mat generated on the server side.

**Comment by xdg2016** [comment]
Thanks, I can run the DMAN_demo.m successfully. I want to know how could I train my own spatial_temporal_attention_model? how should I organize the train data and groundtruth? Waiting for your reply.@jizhu1023

**Comment by yujun0-0** [comment]
Hi,@xdg2016 I meet the problem "Error using load could not read the file 'similarity.mat'. There are no such files or directories."  in matlab.  I wonder how you solved it? Would you please help me?  Thanks a lot!

**Comment by xdg2016** [comment]
你好，我发现这个是编码问题，你可以看我的博客https://blog.csdn.net/sinat_33486980/article/details/95078922
@yujun0-0

**Comment by jizhu1023** [comment]
> Thanks, I can run the DMAN_demo.m successfully. I want to know how could I train my own spatial_temporal_attention_model? how should I organize the train data and groundtruth? Waiting for your reply.@jizhu1023

I will refactor the training code and push it to this repo.

**Comment by jizhu1023** [comment]
> Hi,@xdg2016 I meet the problem "Error using load could not read the file 'similarity.mat'. There are no such files or directories." in matlab. I wonder how you solved it? Would you please help me? Thanks a lot!

Did you use python 2.7? The python scripts need to be adjusted for python 3.

**Comment by yujun0-0** [comment]
Hi, @jizhu1023. I used python 2.7, and I can run successfully now by changing the coding scheme 'utf-8' in calculate_similarity.py.  Thanks a lot! @xdg2016. 
I found that it needs about 7 mins in the first frame to create the ECO trackers(by Geforce GTX TITAN X).
Also, I want to know how to get the initial trackers.
